# Настройки #

# Путь до базы данных Access
dbUrl: C:/ProgramData/STAHLWILLE/Sensomaster4/Database.accdb

# Имя Таблицы
tableName: TohnichiSTC2-G

# COM порт
portName: COM3

# Папка с автоматическими отчетами в pdf
prUrl: C:/TohnichiSTC2-G